name: pullpush
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: "gcfr-352018"
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Pull
      run: docker pull node:18.4.0-alpine

    - name: Tag
      run: docker tag node:18.4.0-alpine eu.gcr.io/${{ env.PROJECT }}/node:2
        
    - name: Push
      run: docker push eu.gcr.io/${{ env.PROJECT }}/node:2
